RentACarSample/Entities/Car.cs
using System.ComponentModel.DataAnnotations;

namespace RentACarSample.Entities
{
    public class Car
    {
        [Key]
        public int Id { get; set; }

        [StringLength(300)]
        public string Plate { get; set; }

        [Display(Name = "Daily Price")]
        [StringLength(300)]
        public decimal DailyPrice { get; set; }

        [Display(Name = "Is Available")]
        public bool IsAvailable { get; set; }

        [Display(Name = "Brand")]
        public int BrandId { get; set; }

        [Display(Name = "Sub Brand")]
        public int SubBrandId { get; set; }

        public Brand Brand { get; set; }
        public SubBrand SubBrand { get; set; }

        public List<Rent> Rents { get; set; }
    }
}

RentACarSample/Areas/Admin/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentACarSample.Areas.Admin.Models;
using RentACarSample.Entities;

namespace RentACarSample.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CarController : Controller
    {
        private DatabaseContext _databaseContext;

        public CarController(DatabaseContext databaseContext)
        {
            _databaseContext = databaseContext;
        }

        // GET: CarController
        public ActionResult Index()
        {
            List<Car> cars = _databaseContext.Cars.Include(x => x.Brand).Include(x => x.SubBrand).ToList();
            return View(cars);
        }

        // GET: Car/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Car/Create
        public ActionResult Create()
        {
            CarCreateViewModel model = new CarCreateViewModel();
            model.Brands = new SelectList(_databaseContext.Brands.ToList(),
                    nameof(Brand.Id), nameof(Brand.Name));

            return View(model);
        }

        // POST: Car/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CarCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                Car car = new Car()
                {
                    BrandId = model.BrandId,
                    SubBrandId = model.SubBrandId,
                    Plate = model.Plate,
                    DailyPrice = model.DailyPrice,
                    IsAvailable = model.IsAvailable,
                };

                _databaseContext.Cars.Add(car);
                _databaseContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }

            model.Brands = new SelectList(_databaseContext.Brands.ToList(),
                    nameof(Brand.Id), nameof(Brand.Name));

            return View(model);
        }


        // GET: Admin/Car/GetSubBrands?brandId=1
        public IActionResult GetSubBrands(int brandId)
        {
            List<SubBrand> subBrands =
                _databaseContext.SubBrands.Where(x => x.BrandId == brandId).ToList();

            return PartialView("_SubBrandsPartial", subBrands);
        }

        // GET: Car/Edit/5
        public ActionResult Edit(int id)
        {
            Car car = _databaseContext.Cars.Find(id);

            if (car == null)
            {
                return RedirectToAction(nameof(Index));
            }

            CarEditViewModel model = new CarEditViewModel();
            model.Plate = car.Plate;
            model.DailyPrice = car.DailyPrice;
            model.IsAvailable = car.IsAvailable;
            model.BrandId = car.BrandId;
            model.SubBrandId = car.SubBrandId;

            model.Brands = new SelectList(_databaseContext.Brands.ToList(),
                    nameof(Brand.Id), nameof(Brand.Name));

            model.SubBrands = new SelectList(_databaseContext.SubBrands.Where(x => x.BrandId == car.BrandId).ToList(),
                    nameof(SubBrand.Id), nameof(SubBrand.Name));

            return View("Edit2", model);
        }

        // POST: Car/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CarEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                Car car = _databaseContext.Cars.Find(id);

                if (car != null)
                {
                    car.Plate = model.Plate;
                    car.DailyPrice = model.DailyPrice;
                    car.IsAvailable = model.IsAvailable;
                    car.BrandId = model.BrandId;
                    car.SubBrandId = model.SubBrandId;

                    _databaseContext.SaveChanges();
                }

                return RedirectToAction(nameof(Index));
            }

            model.Brands = new SelectList(_databaseContext.Brands.ToList(),
                    nameof(Brand.Id), nameof(Brand.Name));

            model.SubBrands = new SelectList(_databaseContext.SubBrands.Where(x => x.BrandId == model.BrandId).ToList(),
                    nameof(SubBrand.Id), nameof(SubBrand.Name));

            return View("Edit2", model);
        }

        // GET: Car/Delete/5
        public ActionResult Delete(int id)
        {
            Car car = _databaseContext.Cars.Find(id);

            _databaseContext.Cars.Remove(car);
            //_databaseContext.Remove(car);
            _databaseContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // POST: Car/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

RentACarSample/Areas/Admin/Views/Car/Create.cshtml
@model CarCreateViewModel


<partial name="_PageTitlePartial" model="@("Create Car")" />

<div class="row">
    <div class="col">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>

            <div class="form-group mb-3">
                <label asp-for="BrandId" class="control-label"><b>Brand</b></label>
                <select asp-for="BrandId" class="form-select" asp-items="@Model.Brands" onchange="brandOnChange()">
                    <option value="">Seçiniz</option>
                </select>
            </div>

            <div class="form-group mb-3">
                <label asp-for="SubBrandId" class="control-label"><b>Sub Brand</b></label>
                <select asp-for="SubBrandId" class="form-select">
                    <option value="">Seçiniz</option>
                </select>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Plate" class="control-label">Plate</label>
                <input asp-for="Plate" class="form-control" />
                <span asp-validation-for="Plate" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="DailyPrice" class="control-label">Daily Price</label>
                <input asp-for="DailyPrice" class="form-control" />
                <span asp-validation-for="DailyPrice" class="text-danger"></span>
            </div>

            <div class="form-group form-check mb-3">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAvailable" /> Is Available
                </label>
            </div>

            <div class="form-group mb-3">
                <button type="submit" class="btn btn-primary btn-sm">Create</button>
            </div>
        </form>
    </div>
</div>

<script>
    function brandOnChange(){
        var brandId = $("#BrandId").val();
        var url = '/Admin/Car/GetSubBrands?brandId=' + brandId;

        $("#SubBrandId").load(url);
    }
</script>

RentACarSample/Areas/Admin/Views/Car/Edit.cshtml
@model CarEditViewModel


<partial name="_PageTitlePartial" model="@("Edit Car")" />

<div class="row">
    <div class="col">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>

            <div class="form-group mb-3">
                <label asp-for="BrandId" class="control-label"><b>Brand</b></label>
                <select asp-for="BrandId" class="form-select" asp-items="@Model.Brands" onchange="brandOnChange()">
                    <option value="">Seçiniz</option>
                </select>
            </div>

            <div class="form-group mb-3">
                <label asp-for="SubBrandId" class="control-label"><b>Sub Brand</b></label>
                <select asp-for="SubBrandId" class="form-select">
                    <option value="">Seçiniz</option>
                </select>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Plate" class="control-label">Plate</label>
                <input asp-for="Plate" class="form-control" />
                <span asp-validation-for="Plate" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="DailyPrice" class="control-label">Daily Price</label>
                <input asp-for="DailyPrice" class="form-control" />
                <span asp-validation-for="DailyPrice" class="text-danger"></span>
            </div>

            <div class="form-group form-check mb-3">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAvailable" /> Is Available
                </label>
            </div>

            <div class="form-group mb-3">
                <button type="submit" class="btn btn-primary btn-sm">Save</button>
            </div>
        </form>
    </div>
</div>

@section MenuExtra{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Car" asp-action="Create">Create Car</a>
    </li>
}

@section Styles{
    <style>
        .test {
            color: red;
        }
    </style>
}

@section Scripts{

    <script>

        $(function () {
            // sayfa yüklendikten sonra çalışacak js kodu.
            brandOnChange();
        });

        //$(document).ready(function(){
        //    // sayfa yüklendikten sonra çalışacak js kodu.
        //});

        //document.addEventListener("DOMContentLoaded",function(){
        //    // sayfa yüklendikten sonra çalışacak js kodu.
        //});

        function brandOnChange() {
            var brandId = $("#BrandId").val();
            var url = '/Admin/Car/GetSubBrands?brandId=' + brandId;

            $("#SubBrandId").load(url, function () {
                $("#SubBrandId").val(@Model.SubBrandId);
            });
        }

        @*@if (Model.IsAvailable)
        {
            @:alert('Araç uygundur!');
        }*@
    </script>

    @*@if (Model.IsAvailable)
    {
        <script>
            alert('Araç uygundur!');
        </script>
    }*@
}

RentACarSample/Areas/Admin/Views/Car/Edit2.cshtml
@model CarEditViewModel


<partial name="_PageTitlePartial" model="@("Edit Car")" />

<div class="row">
    <div class="col">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>

            <div class="form-group mb-3">
                <label asp-for="BrandId" class="control-label"><b>Brand</b></label>
                <select asp-for="BrandId" class="form-select" asp-items="@Model.Brands" onchange="brandOnChange()">
                    <option value="">Seçiniz</option>
                </select>
            </div>

            <div class="form-group mb-3">
                <label asp-for="SubBrandId" class="control-label"><b>Sub Brand</b></label>
                <select asp-for="SubBrandId" class="form-select" asp-items="@Model.SubBrands">
                    <option value="">Seçiniz</option>
                </select>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Plate" class="control-label">Plate</label>
                <input asp-for="Plate" class="form-control" />
                <span asp-validation-for="Plate" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="DailyPrice" class="control-label">Daily Price</label>
                <input asp-for="DailyPrice" class="form-control" />
                <span asp-validation-for="DailyPrice" class="text-danger"></span>
            </div>

            <div class="form-group form-check mb-3">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAvailable" /> Is Available
                </label>
            </div>

            <div class="form-group mb-3">
                <button type="submit" class="btn btn-primary btn-sm">Save</button>
            </div>
        </form>
    </div>
</div>

@section MenuExtra{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Car" asp-action="Create">Create Car</a>
    </li>
}

@section Styles{
    <style>
        .test {
            color: red;
        }
    </style>
}

@section Scripts{

    <script>
        function brandOnChange() {
            var brandId = $("#BrandId").val();
            var url = '/Admin/Car/GetSubBrands?brandId=' + brandId;

            $("#SubBrandId").load(url);
        }
    </script>
}

RentACarSample/Areas/Admin/Views/Car/Index.cshtml
@model IEnumerable<Car>

@{
    ViewData["Title"] = "Cars";
}

<partial name="_PageTitlePartial" model="@ViewData["Title"]" />

<div class="row mb-3">
    <div class="col">
        <a asp-action="Create" class="btn btn-primary btn-sm">Create New</a>
    </div>
</div>

<table class="table table-bordered table-sm table-hover text-center">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Plate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DailyPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsAvailable)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BrandId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubBrandId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Car item in Model)
        {
            <tr>
                <td>
                    @item.Plate
                </td>
                <td>
                    @item.DailyPrice
                </td>
                <td>
                    @if (item.IsAvailable)
                    {
                        <i class="bi bi-check-circle text-success"></i>
                    }
                    else
                    {
                        <i class="bi bi-x-circle text-danger"></i>
                    }
                </td>
                <td>
                    @item.Brand.Name
                </td>
                <td>
                    @item.SubBrand.Name
                </td>
                <td>
                    <a class="btn btn-warning btn-sm" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    @*<a class="btn btn-info btn-sm" asp-action="Details" asp-route-id="@item.Id">Details</a>*@
                    <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@item.Id" onclick="return confirm('@item.Plate plakalı aracı silmek istediğinize emin misiniz?')">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

RentACarSample/Areas/Admin/Views/Car/_SubBrandsPartial.cshtml
@model List<SubBrand>

<option value="">Seçiniz</option>

@foreach (SubBrand sb in Model)
{
    <option value="@sb.Id">@sb.Name</option>
}